api_platform:
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']