version: "3.4"

services:
    symfony:
      build: ./docker/symfony
      container_name: symfony
      volumes:
        - ${SYMFONY_PATH}:/var/www/app
      tty: true
      depends_on:
        - db
        - maildev
      env_file:
        - ./.env
      ports:
        - "8080:80"
      networks:
          - "default"

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=dispojob"
            - "MYSQL_PASSWORD=dispojob"
            - "MYSQL_DATABASE=dispojob"
        volumes:
            - "db:/var/lib/mysql:rw"
            - "./docker/db/my.cnf:/etc/mysql/my.cnf:ro"
        networks:
            - "default"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      ports:
        - 8181:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_USER=root
        - PMA_PASSWORD=root
        - PMA_HOST=db
        - PMA_PORT=3306
    maildev:
      image: djfarrelly/maildev
      container_name: sf4_maildev
      ports:
      - 8001:80
networks:
    default: {}
volumes:
  db: {}
