fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
france_connect:
    resource: App\Controller\FranceConnectController
    type:     annotation
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
<<<<<<< HEAD

blog:
    resource: App\Controller\Blog\BlogController
    type: annotation
    prefix: /blog
=======
authentication_token:
    path: /authentication_token
    methods: ['POST']
>>>>>>> c772e7e0c767d2d118e72f37d611c113f4ee5019
